export const siteConfig = {
  name: "Naitik Yadav",
  title: "Backend & Systems Enthusiast | Full-Stack Developer",
  description: "Portfolio website of Naitik Yadav",
  accentColor: "#6366f1",
  social: {
    email: "naitik.yadav641@gmail.com",
    linkedin: "https://linkedin.com/in/naitikyadav15",
    twitter: "https://x.com/naitik15dev",
    github: "https://github.com/yanaix10",
  },
  aboutMe:
    "I am Naitik Yadav, a 3rd-year B.Tech Computer Science & Engineering student at SRM University AP. I love building high-performance web applications, engineering scalable backend architectures, and deep-dive code debugging. Passionate about systems programming and open-source software, I actively contribute to projects like OpenSearch (Linux Foundation / AWS) and develop on Arch Linux as my daily driver.",
  skills: [
    "Python",
    "Go",
    "C++",
    "JavaScript",
    "TypeScript",
    "Bash",
    "C",
    "FastAPI",
    "Node.js",
    "Express.js",
    "MongoDB",
    "PostgreSQL",
    "MySQL",
    "Redis",
    "Firebase",
    "React",
    "Tailwind CSS",
    "Vite",
    "HTML5",
    "CSS3",
    "Linux",
    "Docker",
    "Git",
    "GitHub",
    "Postman",
    "CMake",
    "Socket.io",
    "Playwright",
  ],
  projects: [
    {
      name: "VulnPulse: Distributed DAST Engine",
      description:
        "Standalone Dynamic Application Security Testing platform combining a headless browser crawler with concurrent heuristic fuzzers. Features 10+ modular OWASP checks, automated PoC generation, CVSS v3.1 scoring, and a real-time SOC command center dashboard.",
      link: "https://vulnpulse.vercel.app/",
      github: "https://github.com/yanaix10/vulnscan",
      demo: "https://vulnpulse.vercel.app/",
      skills: ["FastAPI", "Python", "Playwright", "React", "SQLAlchemy"],
    },
    {
      name: "Mini-Redis: Concurrent Key-Value Store",
      description:
        "Thread-safe in-memory database built from scratch using POSIX sockets and a custom thread pool to handle concurrent requests. Implements LRU cache eviction, Append-Only File (AOF) crash recovery persistence, and a custom command parser.",
      link: "https://github.com/yanaix10/mini-redis",
      github: "https://github.com/yanaix10/mini-redis",
      demo: null,
      skills: ["C++", "POSIX Threads", "CMake", "Concurrency", "Sockets"],
    },
    {
      name: "SkillSphere: Real-Time Coding Arena",
      description:
        "1v1 competitive coding challenge system with sub-100ms real-time synchronization between peers. Integrated Monaco Editor with Piston API for live sandboxed multi-language code execution and interactive matchmaking lobbies.",
      link: "https://xskillsphere.vercel.app/",
      github: "https://github.com/yanaix10/Skill-Sphere-",
      demo: "https://xskillsphere.vercel.app/",
      inProgress: true,
      skills: ["React", "Node.js", "Socket.io", "MongoDB", "Tailwind CSS"],
    },
    {
      name: "Doodle.io: Collaborative Canvas Game",
      description:
        "Multiplayer real-time drawing and guessing game featuring sub-50ms canvas stroke broadcasting. Built proximity guess matching via Levenshtein distance, automated DoodleBot practice lobbies, and room-based session management.",
      link: "https://doodle-io-lake.vercel.app/",
      github: "https://github.com/yanaix10/Doodle.io",
      demo: "https://doodle-io-lake.vercel.app/",
      skills: ["React", "Node.js", "Socket.io", "Express", "HTML5 Canvas"],
    },
  ],
  openSourceContributions: [
    {
      repo: "opensearch-project/opensearch-go",
      org: "OpenSearch (Linux Foundation / AWS)",
      repoUrl: "https://github.com/opensearch-project/opensearch-go",
      prNumber: 950,
      prUrl: "https://github.com/opensearch-project/opensearch-go/pull/950",
      title: "Route Bulk Requests by DocumentID to Dedicated Worker Channels",
      status: "merged",
      category: "Distributed Systems & Go",
      keyPoints: [
        "Eliminated thread contention in high-throughput bulk indexing by replacing a single shared channel with worker-partitioned queues (`[]chan BulkIndexerItem`).",
        "Implemented deterministic routing using OpenSearch `shardhash.Hash(docID) % NumWorkers` to ensure sequential mutations per document without out-of-order shard writes.",
        "Added lock-free round-robin fallback distribution via `atomic.Uint64` for unkeyed documents and safe concurrent channel draining in `Close()`.",
      ],
      skills: ["Go", "Concurrency", "OpenSearch", "Linux", "Git"],
      date: "Jul - Aug 2026",
    },
    {
      repo: "opensearch-project/opensearch-api-specification",
      org: "OpenSearch (Linux Foundation / AWS)",
      repoUrl: "https://github.com/opensearch-project/opensearch-api-specification",
      prNumber: 1229,
      prUrl: "https://github.com/opensearch-project/opensearch-api-specification/pull/1229",
      issueNumber: 1132,
      issueUrl: "https://github.com/opensearch-project/opensearch-api-specification/issues/1132",
      title: "Make ExplainAnalyzeToken.termFrequency Optional in Analyze Schema",
      status: "in-review",
      category: "API Specs & SDKs",
      keyPoints: [
        "Fixed strict deserialization exceptions (`missing property: termFrequency`) in generated clients like `opensearch-java 3.1.0` when calling `_analyze` with `explain: true`.",
        "Verified core analyzer emission rules and removed `termFrequency` from the `required` array in `indices.analyze.yaml` for standard analyzer compatibility.",
      ],
      skills: ["OpenSearch", "Git", "GitHub"],
      date: "Sep 2026",
    },
    {
      repo: "o19s/chorus-opensearch-edition",
      org: "OpenSource Connections (Chorus)",
      repoUrl: "https://github.com/o19s/chorus-opensearch-edition",
      prNumber: 190,
      prUrl: "https://github.com/o19s/chorus-opensearch-edition/pull/190",
      issueNumber: 189,
      issueUrl: "https://github.com/o19s/chorus-opensearch-edition/issues/189",
      title: "Fix Shopping Cart State Desync & Establish Playwright CI Pipeline",
      status: "in-review",
      category: "Search & Frontend",
      keyPoints: [
        "Replaced brittle direct DOM mutations with a decoupled `cart_updated` custom event bus and structured JSON serialization in `sessionStorage`.",
        "Upgraded Docker container runtime to Node 20 and established an automated Playwright E2E integration test suite in GitHub Actions CI.",
      ],
      skills: ["React", "Playwright", "Docker", "JavaScript", "GitHub"],
      date: "Sep 2026",
    },
    {
      repo: "o19s/chorus-opensearch-edition",
      org: "OpenSource Connections (Chorus)",
      repoUrl: "https://github.com/o19s/chorus-opensearch-edition",
      prNumber: 192,
      prUrl: "https://github.com/o19s/chorus-opensearch-edition/pull/192",
      issueNumber: 191,
      issueUrl: "https://github.com/o19s/chorus-opensearch-edition/issues/191",
      title: "Implement Product Detail Page & Decouple Telemetry Events",
      status: "in-review",
      category: "Search & Frontend",
      keyPoints: [
        "Integrated React Router v6 for dual-layout routing (`/` search and `/product/:asin` PDP) with lightweight on-demand OpenSearch query execution.",
        "Decoupled search card click telemetry (`trackClick()`) from cart conversion UBI events to prevent metric corruption in relevance models.",
      ],
      skills: ["React", "OpenSearch", "JavaScript", "Vite", "HTML5"],
      date: "Sep 2026",
    },
    {
      repo: "o19s/quepid",
      org: "OpenSource Connections (Quepid)",
      repoUrl: "https://github.com/o19s/quepid",
      prNumber: 1726,
      prUrl: "https://github.com/o19s/quepid/pull/1726",
      issueNumber: 1725,
      issueUrl: "https://github.com/o19s/quepid/issues/1725",
      title: "Resolve Local Docker Setup Blockers & Database Provisioning",
      status: "merged",
      category: "DevOps & Infrastructure",
      keyPoints: [
        "Fixed background worker boot crash in `config/queue.yml` by explicitly casting `SOLID_QUEUE_POLLING` environment variable to float (`.to_f`).",
        "Resolved Nginx 502 Bad Gateway via port fallback correction (`${APP_PORT:-3000}:3000`) and resolved MySQL container startup race conditions.",
      ],
      skills: ["Docker", "MySQL", "Linux", "Git"],
      date: "Jun 2026",
    },
    {
      repo: "o19s/quepid",
      org: "OpenSource Connections (Quepid)",
      repoUrl: "https://github.com/o19s/quepid",
      prNumber: 1729,
      prUrl: "https://github.com/o19s/quepid/pull/1729",
      issueNumber: 1722,
      issueUrl: "https://github.com/o19s/quepid/issues/1722",
      title: "Remove Legacy TLS Protocol Redirects & Blank Warning Modals",
      status: "in-review",
      category: "Search & Frontend",
      keyPoints: [
        "Removed deprecated HTTP/TLS protocol verification in `mainCtrl.js` that caused empty warning dialogs to block search engine endpoint configuration.",
        "Cleaned up obsolete `checkTLSForSearchEngineUrl()` modal validation and updated Jasmine test suites in `wizardModal_spec.js`.",
      ],
      skills: ["JavaScript", "Docker", "Git"],
      date: "Jun 2026",
    },
    {
      repo: "o19s/chorus-opensearch-edition",
      org: "OpenSource Connections (Chorus)",
      repoUrl: "https://github.com/o19s/chorus-opensearch-edition",
      prNumber: 188,
      prUrl: "https://github.com/o19s/chorus-opensearch-edition/pull/188",
      issueNumber: 187,
      issueUrl: "https://github.com/o19s/chorus-opensearch-edition/issues/187",
      title: "Fix Analytics Session Persistence & Brand Filter Field Mappings",
      status: "in-review",
      category: "Search & Frontend",
      keyPoints: [
        "Persisted `client_id` and `session_id` in `localStorage` and `sessionStorage` to prevent analytics session drops on page reload.",
        "Corrected schema field casing (`Brand.keyword` → `brand.keyword`) in ReactiveSearch components to restore broken brand faceted filtering.",
      ],
      skills: ["React", "OpenSearch", "JavaScript"],
      date: "Sep 2026",
    },
  ],
  experience: [
    {
      company: "OpenSearch (Linux Foundation / AWS)",
      title: "Open Source Contributor — Go SDK & API Specifications",
      dateRange: "Jul 2026 - Present",
      link: "https://github.com/opensearch-project",
      bullets: [
        "Authored PR #950 (Merged) in the official OpenSearch Go SDK (`opensearchutil`), replacing single-channel bulk ingestion with worker-partitioned queues to eliminate thread contention under heavy indexing loads.",
        "Implemented deterministic per-document routing via `shardhash.Hash(docID) % NumWorkers`, guaranteeing sequential consistency for concurrent updates, backed by an atomic lock-free round-robin fallback.",
        "Authored PR #1229 in the OpenSearch OpenAPI Specification, fixing a strict deserialization exception in `opensearch-java 3.1.0` and multi-language client generators for standard analyzer queries.",
      ],
    },
    {
      company: "Chorus & Quepid (OpenSource Connections)",
      title: "Open Source Contributor — Search Relevance Platforms & DevOps",
      dateRange: "Jun 2026 - Present",
      link: "https://github.com/o19s",
      bullets: [
        "Authored PR #1726 (Merged) in Quepid, resolving 4 critical developer setup blockers across Solid Queue float parsing, Nginx 502 port fallbacks, and MySQL socket race conditions.",
        "Authored PR #190 in Chorus OpenSearch Edition, replacing direct DOM mutation with an event-driven `cart_updated` bus, upgrading to Node 20, and introducing a complete Playwright CI testing pipeline.",
        "Authored PR #192 implementing dynamic Product Detail routing with React Router v6 and isolating search result click telemetry from shopping cart conversion events.",
      ],
    },
  ],
  education: [
    {
      school: "SRM University, AP",
      degree: "Bachelor of Technology in Computer Science and Engineering",
      dateRange: "2024 - 2028",
      link: "https://www.srmap.edu.in/",
      achievements: [
        "Current CGPA: 8.40",
        "Focused Coursework: Data Structures & Algorithms, Operating Systems, Computer Networks, Database Management Systems, System Design",
      ],
    },
    {
      school: "VidyaGyan School (CBSE)",
      degree: "Higher Secondary & Secondary Education",
      dateRange: "2020 - 2024",
      link: "https://vidyagyan.in/",
      achievements: [
        "Higher Secondary (Class XII): 88.4%",
        "Secondary School (Class X): 95.4%",
      ],
    },
  ],
};
